CREATE TABLE IF NOT EXISTS amigos (
  uuid VARCHAR(36) PRIMARY KEY,
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS burros (
  uuid VARCHAR(36) PRIMARY KEY,
  created_by VARCHAR(36) NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  CONSTRAINT fk_amigos_uuid FOREIGN KEY (created_by) REFERENCES amigos(uuid)
);

CREATE TABLE IF NOT EXISTS churros (
  uuid VARCHAR(36) PRIMARY KEY,
  burro_uuid VARCHAR(36) NOT NULL,
  created_by VARCHAR(36) NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  CONSTRAINT fk_burros_uuid FOREIGN KEY (burro_uuid) REFERENCES burros(uuid),
  CONSTRAINT fk_amigos_uuid FOREIGN KEY (created_by) REFERENCES amigos(uuid)
);